# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2019"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Visual Studio 2019 for Windows
      if: matrix.os == 'windows-2019'
      uses: microsoft/setup-msbuild@v1.1
    - name: Install PyMuPDF on Windows
      if: matrix.os == 'windows-2019'
      run: |
            [bool] $vsSetupExists = $null -ne (Get-Command Get-VSSetupInstance -ErrorAction SilentlyContinue)
            if (!$vsSetupExists)
            {
              Write-Verbose "Installing the VSSetup module..."
              Install-Module VSSetup -Scope CurrentUser -Force
            }
            [string] $visualStudioInstallationPath = (Get-VSSetupInstance | Select-VSSetupInstance -Latest -Require Microsoft.Component.MSBuild).InstallationPath
            $env:PYMUPDF_SETUP_DEVENV = (Get-ChildItem $visualStudioInstallationPath -Recurse -Filter "DevEnv.exe" | Select-Object -First 1).FullName
            curl -OL http://prdownloads.sourceforge.net/swig/swigwin-4.1.1.zip
            tar -xf swigwin-4.1.1.zip -C .
            ./swigwin-4.1.1/swig.exe
            git clone https://github.com/pymupdf/PyMuPDF.git
            cd PyMuPDF
            python setup.py install
            cd ..
    - name: Install dependencies
      run: |
        pip install setuptools --upgrade
        pip install --upgrade pip
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pathlib
        python -m pip install opencv-python
        python -m pip install numpy
        python -m pip install matplotlib
        python -m pip install paddleocr==2.6.1.3
        python -m pip install paddlepaddle
        mkdir ~/.config/matplotlib/
        echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run entry point
      run: |
        pip install .
        PlotScan figures/trimmed.png
    - name: Test with pytest
      run: |
        pytest
    - name: Generate Report
      run: |
        pip install codecov
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
        codecov
    - name: See coverage
      run: |
          ls
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS,PYTHON
        files: ./coverage.xml
        flags: tests
    - name: Pushing reports to Codacy (Windows)
      if: matrix.os == 'windows-2019'
      run: |
            git clone https://github.com/codacy/codacy-coverage-reporter.git
            cd codacy-coverage-reporter
            sbt assembly
            $jar = Convert-Path ../codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-*.jar
            java -jar $jar report -r ../coverage.xml --project-token ${{secrets.CODACY_TOKEN}}
    - name: Pushing reports to Codacy (others)
      if: matrix.os != 'windows-2019'
      run: |
            export CODACY_PROJECT_TOKEN=${{secrets.CODACY_TOKEN}}
            LATEST_VERSION="$(curl -Ls https://artifacts.codacy.com/bin/codacy-coverage-reporter/latest)"
            curl -Ls -o codacy-coverage-reporter-assembly.jar "https://artifacts.codacy.com/bin/codacy-coverage-reporter/${LATEST_VERSION}/codacy-coverage-reporter-assembly.jar"
            java -jar codacy-coverage-reporter-assembly.jar report -r coverage.xml

